trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    clean: true
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      configuration: release