trigger:
- master

pool:
  vmImage: windows-latest
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'Client'
- task: Npm@1
  displayName: 'run and build'
  inputs:
    command: 'custom'
    workingDir: 'Client'
    customCommand: 'run build'
- task: DotNetCoreCLI@2
  displayName: '.net restore'
  inputs:
    command: 'restore'
    projects: 'Angular_ASPNETCore_CustomersService.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: '.net build'
  inputs:
    command: 'build'
    projects: 'Angular_ASPNETCore_CustomersService.sln'
- task: DotNetCoreCLI@2
  displayName: '.net publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: PublishBuildArtifacts@1
  displayName: 'publish artifact backend'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/bin/Debug/netcoreapp5.0'
    ArtifactName: 'Backend'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  displayName: 'publish artifact frontend'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/AngularCLI-ASPNET-Core-CustomersService/wwwroot'
    ArtifactName: 'Frontend'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Backend'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'Frontend'
    downloadPath: '$(System.ArtifactsDirectory)'

