trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    clean: true
  - task: DotNetCoreCLI@2
    displayName: 'restore .net'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      configuration: release

  - task: DotNetCoreCLI@2
    displayName: 'build .net'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      configuration: release

  - task: DotNetCoreCLI@2
    displayName: 'publish .net'
    inputs:
      command: 'publish'
      publishWebProjects: true
      configuration: release
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/bin/Release/netcoreapp5.0'
      ArtifactName: 'Backend'
      publishLocation: 'Container'

  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'Client'
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'
      workingDir: 'Client'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/wwwroot'
      ArtifactName: 'wwwroot'
      publishLocation: 'Container'