trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    clean: true
  - task: DotNetCoreCLI@2
    displayName: 'restore .net'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      configuration: release

  - task: DotNetCoreCLI@2
    displayName: 'build .net'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      configuration: release

  - task: DotNetCoreCLI@2
    displayName: 'publish .net'
    inputs:
      command: 'publish'
      publishWebProjects: true
      configuration: release
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'pwd'
  
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: '/AngularCLI-ASPNET-Core-CustomersService/Client'
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run build'
      workingDir: '/AngularCLI-ASPNET-Core-CustomersService/Client'