trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    clean: true
  - task: DotNetCoreCLI@2
    displayName: 'restore .net'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: 'build .net'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      configuration: release

  - task: DotNetCoreCLI@2
    displayName: 'publish .net'
    inputs:
      command: 'publish'
      publishWebProjects: true