trigger:
- master

pool:
  vmImage: windows-latest
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'Client'
- task: Npm@1
  displayName: 'run and build'
  inputs:
    command: 'custom'
    workingDir: 'Client'
    customCommand: 'run build'
- task: DotNetCoreCLI@2
  displayName: '.net restore'
  inputs:
    command: 'restore'
    projects: 'Angular_ASPNETCore_CustomersService.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: '.net build'
  inputs:
    command: 'build'
    projects: 'Angular_ASPNETCore_CustomersService.sln'





